### ISSUE TITLE
Rendered obj axis is not correct

### ISSUE THREAD

**Issue by christopi** [TencentARC/InstantMesh#148]
regarding the X,Y, Z axis, I rendered an car object created with this model and viewed on blender but the axis is not correct
![image](https://github.com/user-attachments/assets/1a1e7b88-f81e-433e-ae3d-b783d361db15)

axis should be like this

![image](https://github.com/user-attachments/assets/a6d062d9-b787-4659-8b51-bc469f503537)

Please help me for switching the axis after model generation

**Comment by christopi** [comment]
I fixed this issue
please feel free to reach out to me if you have any doubt on it

**Comment by LRMridiot** [comment]
@christopi I wonder how you fixed it, I met the same problem about axis. it's changing the network output or postprocessing using tool like PCA or bbox?

> I fixed this issue please feel free to reach out to me if you have any doubt on it

**Comment by christopi** [comment]
should fix camera angles and rotate after it is rendered as a object using a rotate function

**Comment by LRMridiot** [comment]
is that mean should know input-image's camera angles and then correct it or input images at fixed angle like front view?

**Comment by YiFall** [comment]
@christopi Hello, I know I need to use rotation functions, but I feel that the rotated mesh still doesn't match the original view. How should I adjust the camera angle to make it consistent？

**Comment by JennySeidenschwarz** [comment]
Hey @christopi! could you maybe share the rotation matrix / camera angles you use?

**Comment by INSEASONio** [comment]
guys can anyone help? .obj is textured in mixamo, textured in instant mesh viewer, not textured in blender.... plz help for a project. <3

**Comment by Mxeron** [comment]
I also meet the same problem. I found a solution that align models with Coordinate Axes. But i don't know how to  use blenderproc to solve this problem.
